name: Continuous Delivery of ECS

on:
  push:
    branches:
      - main
    paths:
      - api/**
      - .github/workflows/cd_api.yml

jobs:
  push:
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1 # AWS region
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }} # ARN of IAM role for GitHub Actions

      # NOTE: Assign `with.registry-type: public` in case of ECR Public
      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr
        # with:
        #   registry-type: public

      - name: Build and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.ECR_REPO_NAME }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY . --no-cache
          docker push $ECR_REGISTRY/$ECR_REPOSITORY

      - name: Download task definition
        env:
          TASK_DEFINITION_FAMILY_NAME: ${{ secrets.TASK_DEFINITION_FAMILY_NAME }}
        run: |
          aws ecs describe-task-definition --task-definition $TASK_DEFINITION_FAMILY_NAME --query taskDefinition > task-definition.json

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.json
          cluster: ${{ secrets.ECS_CLUSTER_NAME }}
          service: ${{ secrets.ECS_SERVICE_NAME }}
          wait-for-service-stability: true
